export const HANDLE_COMMON = "HANDLE_COMMON"
export const HANDLE_COMMON_TEST = "HANDLE_COMMON_TEST"

export const HANDLE_PSY_TESR = "HANDLE_PSY_TESR"
export const GET_PSY_LIST = "GET_PSY_LIST"
export const GET_TEST_LIST = "GET_TEST_LIST"
export const PUSH_TEST_RESULT = "PUSH_TEST_RESULT"